destination: ./_site
auto:        true
lsi:         false
server_port: 4000
markdown:    rdiscount
permalink:   none
baseurl:     /blog
pygments:    true
pagination:  true
paginate:    20
name: Jazzin' data - analytics and data vizualization
description: We blog about web and social media analytics, business intelligence, and data visualization techniques.
url: http://dev.mango-is.com/blog/
# production commenting:
# liveFyreId: 327726
# dev commenting (for testing purpose)
liveFyreId: 327730
