destination: ./_site
auto:        true
lsi:         false
server_port: 4000
markdown:    kramdown
permalink:   none
pygments:    true
pagination:  true
paginate:    20
name: Jazzin' data - analytics and data vizualization
description: We blog about web and social media analytics, business intelligence, and data visualization techniques.
url: http://localhost:4000
liveFyreId: 327730
# to run production, user following jekyll command arguments: --url http://dev.mango-is.com --base-url /blog --liveFyreId 327726
